version: '3'
services:

    web:
       image: nginx:latest
       volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
#           - "./etc/ssl:/etc/ssl"
            - ./templates:/templates
#           - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
       ports:
           - "8080:80"
#           - "3000:443"
#       environment:
#           - NGINX_HOST=${NGINX_HOST}
#       command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
       restart: always
       depends_on:
           - app
           - db

    app:
      build: .
      volumes:
        - .:/app
#      ports:
#        - "8080:8080"

    db:
      image: mysql:5.7
      volumes:
        - ./db:/var/lib/mysql
      restart: always
      environment:
      #     MYSQL_ROOT_PASSWORD: secret
      #     MYSQL_DATABASE: wordpress
        MYSQL_USER: root
      #     MYSQL_PASSWORD: secret
      ports:
        - "3306:3306"