version: '3'
services:

    proxy:
       image: nginx:latest
       volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./templates:/templates
       ports:
           - "80:80"
       restart: always
       links:
        - app:app

    app:
      build: .
      volumes:
        - .:/app
      ports:
        - "8080"

    db:
      image: mysql:5.7
      volumes:
        - ./db:/var/lib/mysql
      restart: always
      environment:
        MYSQL_DATABASE: db
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_PASSWORD: secret
      ports:
        - "3306"