version: '3'
services:

    db:
      image: mysql:5.7
      volumes:
        - ./db:/var/lib/mysql
      restart: always
      environment:
        MYSQL_DATABASE: db
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_PASSWORD: secret
      ports:
        - "3306"

    app:
      build: .
      volumes:
        - ./src:/app
        - ./storage:/storage
      ports:
        - "8080"

    proxy:
       image: nginx:latest
       volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log/nginx:/var/log/nginx
       ports:
           - "80:80"
       restart: always
       links:
        - app:app